management:
  endpoints:
    web:
      exposure: # exposes /actuator endpoints over HTTP
        include: '*'
  info:
    env:
      enabled: true # includes environment-specific info in /actuator/info
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      enabled: true # /actuator/shutdown to shut down gracefully (TO BE SECURED)
  health: # /actuator/health
    readinessstate: # /actuator/health/readiness
      enabled: true
    livenessstate: # /actuator/health/liveness
      enabled: true

spring:
  rabbitmq:
    retry-queues-ttl: 2000
    retry-max-count: 3

    notification:
      queue: "notification-queue"
      exchange: "notification-exchange"
      routing-key: "notification-key"

    retry-notification:
      queue: "retry-notification-queue"
      exchange: "retry-notification-exchange"
      routing-key: "retry-notification-key"

    dead-letter:
      queue: "dead-queue"
      exchange: "dead-exchange"
      routing-key: "dead-key"

resilience4j:
  circuitbreaker: # /actuator/circuitbreakers
    configs:
      default: # applied to all circuit breakers; to specify one, use its name
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        permitted-number-of-calls-in-half-open-state: 2
        sliding-window-type: COUNT_BASED
        slow-call-duration-threshold: 3s
        slow-call-rate-threshold: 50
  timelimiter:
    configs:
      default:
        timeout-duration: 5s
        cancel-running-future: true
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 100
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions: # retry only if one of the following exceptions is raised
          - java.util.concurrent.TimeoutException
  ratelimiter:
    configs:
      timeout-duration: 1000
      limit-refresh-period: 1000
      limit-for-period: 3